import GameImage1 from '../public/images/gameImage1.png';
import GameImage2 from '../public/images/gameImage2.png';
import GameImage3 from '../public/images/gameImage3.png';
import GameImage4 from '../public/images/gameImage4.png';

const gameList = [
  {
    id: 0,
    title: '할리갈리',
    img: GameImage1,
    boardGameTitle: 'test',
    new: 'true',
    price: 3000,
    minPlayerCount: 2,
    maxPlayerCount: 4,
    like: true,
    account: 1,
    address: '관악구 신림동',
    time: '3시간 전',
    tag: ['전략', '테마', '전쟁'],
    createdAt: '3시간전',
    interestCount: 1,
  },
  {
    id: 1,
    title: '광기의 저택',
    img: GameImage2,
    boardGameTitle: 'test',
    new: 'true',
    price: 15000,
    minPlayerCount: 3,
    maxPlayerCount: 4,
    like: true,
    account: 14,
    address: '동작구 상도동',
    time: '3시간 전',
    tag: ['전략', '테마', '전쟁'],
    createdAt: '3시간전',
    interestCount: 1,
  },
  {
    id: 2,
    title: '루미큐브',
    img: GameImage3,
    boardGameTitle: 'test',
    new: 'true',
    price: 10000,
    minPlayerCount: 3,
    maxPlayerCount: 5,
    like: true,
    account: 22,
    address: '강남구 압구정동',
    time: '3시간 전',
    tag: ['전략', '테마', '전쟁'],
    createdAt: '3시간전',
    interestCount: 1,
  },
  {
    id: 3,
    title: '달무티',
    img: GameImage4,
    boardGameTitle: 'test',
    new: 'true',
    price: 8000,
    minPlayerCount: 3,
    maxPlayerCount: 6,
    like: true,
    account: 22,
    address: '강남구 압구정동',
    time: '3시간 전',
    tag: ['전략', '테마', '전쟁'],
    createdAt: '3시간전',
    interestCount: 1,
  },
];

export default gameList;
